language: node_js #指定使用的语言

node_js:
  - 14.18.1 #nodejs的匹配版本，最新版使用参数stable

# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules

before_script:
  - export TZ='Asia/Shanghai' # 更改时区
  - echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config  # 跳过ssh认证
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host gitee.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

# Start: Build Lifecycle
install:
  - npm install

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate

# 指定博客分支
branches:
  only:
    - hexo #触发持续集成的分支

env:
 global:
    - GITHUB_HEXOREF: github.com/JimyFengqi/JimyFengqi.github.io.git # github分支
    - GITEE_HEXOREF: gitee.com/JimyFengqi/JimyFengqi.gitee.io.git   # 码云分支

# 设置git提交名，邮箱；替换真实token到_config.yml文件，最后depoy部署
after_script:
  - git clone -b master https://${GITHUB_HEXOREF} .deploy_git
  - mv .deploy_git/.git/ ./public/
  - cd ./public
  - git config user.name "JimyFengqi"
  - git config user.email "jmps515@163.com"
  - git config --list
  - git add .
  - git commit -m "Auto update docs by Travis CI"
  - git log -3
  - git push --force --quiet "https://${GH_TOKEN}@${GITHUB_HEXOREF}" master:master
  - git push --force --quiet "https://${GH_USER}:${GIEE_PASSWORD}@${GITEE_HEXOREF}" master:master
