categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
newer: Newer
older: Older
share: Share
powered_by: Powered by
rss_feed: RSS Feed=
tag: Tag
category: category
archives: archives
about: about
aboutBasicInfo: BasicInfo
age: age
sex: sex
coordinate: coordinate
status: status
skill: skill
socialAccounts: social accounts
game: game
book: book
Menu:
  Home: Home
  Archives: Archives
  Tags: Tags
  Categories: Categories
  Github: Github
  About: About
  link: link

Paginator:
  Prev: Prev
  Next: Next

postCategoryTitle: Article Categories
postTagTitle: Article Tags

copyright:
    author: "author: "
    link: "link: "
    license_title: "Copyright notice: "
    left_license_content: "All articles on this website, unless otherwise stated, adopt "
    right_license_content: "reprint policy. If reproduced, please indicate source!"

friends: friends
keyword: Please enter keywords
reading: reading
totalVisits: Total visits
numberVisitors: Number of visitors

lastArticle: Prev
nextArticle: Next

times: times
people: people

recommendedArticles: Recommend Articles
readMore: Read More
copy: copy
paperCatalog: catalog
loading: loading
publishedIn: Published in
wordcount: 'Words'
min2read: 'Reading time'
min: min
no_title: no title
side:
  side_archives: 'archives'
  more_button: 'more'
categoryRadarTitle: Post Categories Radar Chart
categoryNumber: Number of Categories
categoryEmptyTip: Your posts has no categories information yet.
postCharts: Post Charts
postPublishChart: Post Publish Chart
categoriesChart: Categories Chart
top10TagsChart: TOP10 Tags Chart
postsNumberName: Number of posts
maximum: Maximum
minimum: Minimum
average: Average
myProjects: My Projects
mySkills: My Skills
otherSkills: Other Skills
gallery: Gallery
notag: No tag
from: From
reprint: Reprint policy
author: Author
link: Link
use: All articles in this blog are used except for special statements
licensed: reprint polocy. If reproduced, please indicate source
